apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Software\kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: discount-grpc
  name: discount-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discount-grpc
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Software\kompose\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.25.0 (a70f80cc)
      creationTimestamp: null
      labels:
        io.kompose.service: discount-grpc
    spec:
      containers:
        - image: discountgrpc
          name: discount.grpc
          resources: {}
      restartPolicy: Always
status: {}
