apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Software\kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: shopping-aggregator
  name: shopping-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shopping-aggregator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Software\kompose\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.25.0 (a70f80cc)
      creationTimestamp: null
      labels:
        io.kompose.service: shopping-aggregator
    spec:
      containers:
        - image: shoppingaggregator
          name: shopping.aggregator
          resources: {}
      restartPolicy: Always
status: {}
